Chart0_0:
  ChartType: PhasePlot
  E_max: 200.0
  E_min: 1.0
  cnorm_type: Log
  cpow_num: 0.6
  face_color: gainsboro
  interpolation: nearest
  masked: 1
  mom_dim: 0
  p_max: 2
  p_min: -2.0
  pbins: 200
  prtl_type: 0
  set_E_max: false
  set_E_min: false
  set_p_max: false
  set_p_min: false
  set_v_max: false
  set_v_min: false
  show_cbar: true
  show_int_region: true
  show_shock: false
  spatial_x: true
  spatial_y: false
  twoD: 1
  v_max: 0
  v_min: -2.0
  weighted: false
  xbins: 200
Chart0_1:
  ChartType: PhasePlot
  E_max: 200.0
  E_min: 1.0
  cnorm_type: Log
  cpow_num: 0.6
  face_color: gainsboro
  interpolation: nearest
  masked: 1
  mom_dim: 0
  p_max: 2
  p_min: -2.0
  pbins: 200
  prtl_type: 1
  set_E_max: false
  set_E_min: false
  set_p_max: false
  set_p_min: false
  set_v_max: false
  set_v_min: false
  show_cbar: true
  show_int_region: true
  show_shock: false
  spatial_x: true
  spatial_y: false
  twoD: 1
  v_max: 0
  v_min: -2.0
  weighted: false
  xbins: 200
Chart1_0:
  ChartType: DensityPlot
  OutlineText: true
  UseDivCmap: false
  cmap: None
  cnorm_type: Linear
  cpow_num: 0.6
  dens_type: 0
  div_midpoint: 0.0
  face_color: gainsboro
  interpolation: none
  normalize_density: true
  set_color_limits: false
  set_v_max: false
  set_v_min: false
  show_cbar: true
  show_cpu_domains: false
  show_labels: true
  show_shock: false
  spatial_x: true
  spatial_y: 0
  stretch_colors: false
  twoD: 0
  v_max: 10
  v_min: 0
Chart1_1:
  1D_label:
  - - $B_x$
    - $B_y$
    - $B_z$
  - - $E_x$
    - $E_y$
    - $E_z$
  - - $J_x$
    - $J_y$
    - $J_z$
  - - $B_\mathrm{tot}$
    - $B_\mathrm{tot}$
    - $B_\mathrm{tot}$
  2D_label:
  - - $B_x$
    - $B_y$
    - $B_z$
  - - $E_x$
    - $E_y$
    - $E_z$
  - - $J_x$
    - $J_y$
    - $J_z$
  - - $B_\mathrm{tot}$
    - $B_\mathrm{tot}$
    - $B_\mathrm{tot}$
  ChartType: FieldsPlot
  OneDOnly:
  - false
  - false
  - false
  OutlineText: true
  UseDivCmap: true
  cmap: None
  cmdstr1: '## WHATEVER IS TYPED HERE IS EVALUATED AS PURE PYTHON. THERE IS NO ERROR
    CHECKING

    ## OR ANY SANITIZATION OF USER INPUT. YOU WILL INHERIT THE NAMESPACE OF THE MAIN

    ## PROGRAM, BUT YOU CAN IMPORT OTHER LIBRARIES, DEFINE HELPER FUNCTIONS, WHATEVER.

    ## JUST BE SURE AT SOME POINT YOU DEFINE A FUNCTION NAMED FieldFunc THAT RETURNS

    ## SOMETHING THE SAME SHAPE AS YOUR FIELD ARRAYS. SIMULATION DATA CAN ONLY BE

    ## ACCESSED INSIDE OF FieldFunc.

    #

    ## IT''S EASY TO DO BAD THINGS HERE... TYPE CAREFULLY :)

    #

    #def FieldFunc(bx, by, bz):

    #    # Be sure to include all the neccesary data you need to calculate your

    #    # derived field quantity as arguments to the ''FieldFunc'' function.

    #    # The only valid arguments to field function are things saved in the Tristan

    #    # HDF5 files: e.g., ui, bx, jz...etc. The argumes return the raw tristan
    arrays.

    #

    #    # You must return an array the same shape as the fields array, or an array
    that

    #    # is the same length as the x axis of the simulation (and then checking 1D)

    #

    #    return bx**2+by**2+bz**2

    #    '
  cmdstr2: '## WHATEVER IS TYPED HERE IS EVALUATED AS PURE PYTHON. THERE IS NO ERROR
    CHECKING

    ## OR ANY SANITIZATION OF USER INPUT. YOU WILL INHERIT THE NAMESPACE OF THE MAIN

    ## PROGRAM, BUT YOU CAN IMPORT OTHER LIBRARIES, DEFINE HELPER FUNCTIONS, WHATEVER.

    ## JUST BE SURE AT SOME POINT YOU DEFINE A FUNCTION NAMED FieldFunc THAT RETURNS

    ## SOMETHING THE SAME SHAPE AS YOUR FIELD ARRAYS. SIMULATION DATA CAN ONLY BE

    ## ACCESSED INSIDE OF FieldFunc.

    #

    ## IT''S EASY TO DO BAD THINGS HERE... TYPE CAREFULLY :)

    #

    #def FieldFunc(bx, by, bz):

    #    # Be sure to include all the neccesary data you need to calculate your

    #    # derived field quantity as arguments to the ''FieldFunc'' function.

    #    # The only valid arguments to field function are things saved in the Tristan

    #    # HDF5 files: e.g., ui, bx, jz...etc. The argumes return the raw tristan
    arrays.

    #

    #    # You must return an array the same shape as the fields array, or an array
    that

    #    # is the same length as the x axis of the simulation (and then checking 1D)

    #

    #    return bx**2+by**2+bz**2

    #    '
  cmdstr3: '## WHATEVER IS TYPED HERE IS EVALUATED AS PURE PYTHON. THERE IS NO ERROR
    CHECKING

    ## OR ANY SANITIZATION OF USER INPUT. YOU WILL INHERIT THE NAMESPACE OF THE MAIN

    ## PROGRAM, BUT YOU CAN IMPORT OTHER LIBRARIES, DEFINE HELPER FUNCTIONS, WHATEVER.

    ## JUST BE SURE AT SOME POINT YOU DEFINE A FUNCTION NAMED FieldFunc THAT RETURNS

    ## SOMETHING THE SAME SHAPE AS YOUR FIELD ARRAYS. SIMULATION DATA CAN ONLY BE

    ## ACCESSED INSIDE OF FieldFunc.

    #

    ## IT''S EASY TO DO BAD THINGS HERE... TYPE CAREFULLY :)

    #

    #def FieldFunc(bx, by, bz):

    #    # Be sure to include all the neccesary data you need to calculate your

    #    # derived field quantity as arguments to the ''FieldFunc'' function.

    #    # The only valid arguments to field function are things saved in the Tristan

    #    # HDF5 files: e.g., ui, bx, jz...etc. The argumes return the raw tristan
    arrays.

    #

    #    # You must return an array the same shape as the fields array, or an array
    that

    #    # is the same length as the x axis of the simulation (and then checking 1D)

    #

    #    return bx**2+by**2+bz**2

    #    '
  cnorm_type: Linear
  cpow_num: 1.0
  div_midpoint: 0.0
  face_color: gainsboro
  field_type: 0
  interpolation: none
  normalize_fields: true
  set_v_max: false
  set_v_min: false
  show_FFT_region: false
  show_cbar: true
  show_cpu_domains: false
  show_shock: false
  show_x: 1
  show_y: 1
  show_z: 1
  spatial_x: true
  spatial_y: 0
  stretch_colors: false
  twoD: 0
  v_max: 10
  v_min: 0
  yaxis_label:
  - $B$
  - $E$
  - $J$
  - $B$
Chart2_0:
  BoostedIons: false
  ChartType: SpectraPlot
  DelGame: 0.03
  DelGami: 0.06
  DoPowerLawFitElectron: false
  DoPowerLawFitIon: false
  ElectronLeft: -10000.0
  ElectronRight: 0.0
  GammaElectronInjection: 30.0
  GammaIonInjection: 1.0
  IonLeft: -10000.0
  IonRight: 0.0
  MeasureEpsE: false
  MeasureEpsP: false
  PL_legend_loc: N/A
  PowerLawElectronMax: 10.0
  PowerLawElectronMin: 1.0
  PowerLawIonMax: 10.0
  PowerLawIonMin: 1.0
  PrtlIntegrationRelative: true
  SetTe: false
  SetTi: false
  T_legend_loc: N/A
  eNormalizer: 0.0
  face_color: gainsboro
  iNormalizer: 0.0
  normalize_spectra: true
  rest_frame: false
  set_xlim: true
  set_ylim: true
  show_electrons: 1
  show_ions: 1
  show_legend: true
  spatial_x: false
  spatial_y: false
  spectral_type: 0
  twoD: 0
  x_max: 200
  x_min: 0.05
  y_max: 0
  y_min: -6
Chart2_1:
  ChartType: MagPlots
  OutlineText: true
  UseDivCmap: true
  cmap: None
  cnorm_type: Linear
  cpow_num: 0.6
  div_midpoint: 0.0
  face_color: gainsboro
  interpolation: none
  mag_plot_type: 0
  set_v_max: false
  set_v_min: false
  show_FFT_region: false
  show_cbar: true
  show_cpu_domains: false
  show_shock: false
  spatial_x: true
  spatial_y: 0
  stretch_colors: false
  twoD: 0
  v_max: 10
  v_min: 0
MainParamDict:
  2DSlicePlane: 0
  Average1D: 0
  AxLabelSize: 11
  ClearFig: true
  ColorMap: Blue/Green/Red/Yellow
  ConstantShockVel: true
  DivColorMap: Blue/Green/Red/Yellow
  DoLorentzBoost: false
  FFTLeft: 0.0
  FFTRelative: true
  FFTRight: 200.0
  FFT_color: k
  FigSize:
  - 12.0
  - 6.22
  GammaBoost: 0.0
  HAxesExtent:
  - 18
  - 92
  - 0
  - -1
  HCbarExtent:
  - 0
  - 4
  - 0
  - -1
  HSubPlotParams:
    bottom: 0.06
    hspace: 0.3
    left: 0.06
    right: 0.95
    top: 0.91
    wspace: 0.15
  HorizontalCbars: false
  ImageAspect: 0
  LinkK: true
  LinkSpatial: 1
  LoopPlayback: true
  MaxCols: 8
  MaxRows: 8
  NumFontSize: 11
  NumOfCols: 2
  NumOfRows: 3
  PrtlStride: 5
  Recording: false
  Reload2End: true
  SetkLim: false
  SetxLim: false
  SetyLim: false
  ShowTitle: true
  SkipSize: 5
  VAxesExtent:
  - 4
  - 90
  - 0
  - 92
  VCbarExtent:
  - 4
  - 90
  - 94
  - 97
  VSubPlotParams:
    bottom: 0.06
    hspace: 0.15
    left: 0.06
    right: 0.95
    top: 0.93
    wspace: 0.23
  WaitTime: 0.01
  WindowSize: 1200x700
  annotateTextSize: 18
  cbarLabelPad: 15
  dpi: 100
  electron_color: '#fca636'
  electron_fit_color: yellow
  ion_color: '#d6556d'
  ion_fit_color: r
  kLeft: 0.1
  kRight: 1.0
  legendLabelSize: 11
  shock_color: w
  xLabelPad: 0
  xLeft: 0.0
  xLimsRelative: false
  xRight: 100.0
  yBottom: 0.0
  yLabelPad: 0
  ySlice: 0.5
  yTop: 100.0
  zSlice: 0.0
general:
  ConfigName: Default
